% Save selected files generated by this run

savrun1 = sprintf('cp -f *.mat %s',strtok(runname, '/'));
[status,result]=system(savrun1);

% savrun2 = sprintf('mv *.png %s',strtok(runname, '/'));
% system(savrun2);

savrun3 = sprintf('mv -f *.ps %s',strtok(runname, '/'));
[status,result]=system(savrun3);

%savrun4a = sprintf('cp -f DST*.DAT %s',strtok(runname, '/'));
savrun4a = sprintf('cp -f dst_sample.dst %s',strtok(runname, '/'));
[status,result]=system(savrun4a);

%savrun4b = sprintf('cp -f DST*.OUT %s',strtok(runname, '/'));
savrun4b = sprintf('cp -f DST*.OUT %s',strtok(runname, '/'));
[status,result]=system(savrun4b);

savrun5 = sprintf('cp -f PST* %s',strtok(runname, '/'));
[status,result]=system(savrun5);

savrun6 = sprintf('cp -f gipht.in %s',strtok(runname, '/'));
[status,result]=system(savrun6);

savrun7 = sprintf('cp -f %s %s',txtinname,strtok(runname, '/'));
[status,result]=system(savrun7);

savrun8 = sprintf('cp -f TST* %s',strtok(runname, '/'));
[status,result]=system(savrun8);

savrun9 = sprintf('cp -f gipht_subregion.dat %s',strtok(runname, '/'));
[status,result]=system(savrun9);



